// clip-config.js
window.ANNOTATION_CLIPS = [
  { id: "dissect_energy", label: "Clip 1", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/dissect_energy.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "cut_energy", label: "Clip 2", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/cut_energy.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "seal", label: "Clip 3", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/seal.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "dissect", label: "Clip 4", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/dissect.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "spread", label: "Clip 5", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/spread.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "coagulate2", label: "Clip 6", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/coagulate2.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "grap_pull", label: "Clip 7", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/grap_pull.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "coagulate", label: "Clip 8", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/coagulate.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "cut", label: "Clip 9", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/cut.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_coagulate", label: "Clip 10", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_coagulate.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_push", label: "Clip 11", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_push.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_randommove", label: "Clip 12", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_randommove.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_retract", label: "Clip 13", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_retract.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_clamp", label: "Clip 14", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_clamp.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_coagulate_seal", label: "Clip 15", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_coagulate_seal.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_dissection", label: "Clip 16", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_dissection.mov", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "release", label: "Clip 17", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/release.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "push", label: "Clip 18", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/push.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "camera_move", label: "Clip 19", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/camera_move.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "idle", label: "Clip 20", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/idle.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "specimen_material_removal", label: "Clip 21", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/specimen_material_removal.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "staple", label: "Clip 22", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/staple.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "knot_tying", label: "Clip 23", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/knot_tying.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "needle_drive", label: "Clip 24", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/needle_drive.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "clip", label: "Clip 25", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/clip.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "irrigate", label: "Clip 26", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/irrigate.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "suction", label: "Clip 27", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/suction.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "instrument_introduction", label: "Clip 28", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/instrument_introduction.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "instrument_removal", label: "Clip 29", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/instrument_removal.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." },
  { id: "new_port_placement", label: "Clip 30", src: "https://github.com/mariacmorais/gesture/raw/refs/heads/main/dataset/new_port_placement.mp4", poster: "", prompt: "Please enter the gesture you have identified from this clip." }
];

window.ANNOTATION_SUBMISSION = {
  endpoint: "https://formspree.io/f/mykzvzna",
  method: "POST",
  headers: { Accept: "application/json" },
  additionalFields: { studyId: "gesture-identification" },
  bodyWrapper: "annotation",
  csvMirror: {
    enabled: true,
    endpoint: "https://formspree.io/f/mykzvzna",
    method: "POST",
  },
};
